name: Build YaD

on:
  push:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Rust dependencies 
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: rust-cache-${{ matrix.platform }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-cache-${{ matrix.platform }}-

      - name: Cache Rust build artifacts
        uses: actions/cache@v3
        with:
          path: src-tauri/target
          key: rust-build-${{ matrix.platform }}-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            rust-build-${{ matrix.platform }}-

      - name: Cache node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ matrix.platform }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.platform }}-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc' || '' }}
          override: true

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Tauri CLI 
        run: cargo install tauri-cli 

      - name: Install npm dependencies
        run: npm install
