name: Build YaD

on:
  push:
    branches:
      - dev
  merge:
    branches:
      - main 

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: action-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform == "windows-latest" && 'x86_64-pc-windows-msvc' || '' }}
          override: true

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Tauri CLI 
        run: cargo install tauri-cli 

      - name: Install npm dependencies
        run: npm install
