name: Build YaD

on:
  push:
    branches:
      - dev

concurrency:
  group: "tauriapp-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ runner.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || '' }}
          override: true

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm install

      - name: Install Tauri CLI and Cross
        run: |
          cargo install tauri-cli
          cargo install cross

      - name: Setup cross compilation
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu ${{ matrix.arch }}-pc-windows-msvc ${{ matrix.arch }}-apple-darwin

      - name: Building YaD app for ${{ matrix.os }} and ${{ matrix.arch }}
        run: |
          ls -lh
          if [ "${{ matrix.os  }}" == "ubuntu-latest" ]; then
            cross build --target ${matrix.arch}-unknown-linux-gnu --release
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cross build --target ${matrix.arch}-apple-darwin --release
          else
            cross build --target ${matrix-arch}-pc-windows-msvc --release
          fi

      - name: Build Tauri App 
        run: npm run tauri build -- --release

      - name: Package
        run: |
          if [ "${{matrix.os}}" == "ubuntu-latest" ]; then
            npm run tauri build -- --release --target deb
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run tauri build -- --release --target dmg
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run tauri build -- --release --target msi
          fi
          ls -lha
          ls -lha src-tauri/target/release

